name: "CI"

on:
  [push, pull_request]

jobs:

  server:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    services:
      redis:
          image: redis:alpine
          ports:
              - "6379:6379"

      mongo:
          image: mongo:3.6
          ports:
              - "27017:27017"

      elastic:
          image: elasticsearch:7.7.1
          ports:
              - "9200:9200"
          env:
            discovery.type: single-node

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: 'pip'

    - run: |
        sudo apt-get update
        sudo apt-get -y install libxml2-dev libxmlsec1-dev libxmlsec1-openssl libexempi-dev

    - run: |
        pip install -U pip wheel setuptools
        pip install -r dev-requirements.txt

    - run: flake8

    - run: python manage.py app:initialize_data


  client:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 12

    - run: npm ci

    - run: npm run build
